### ISSUE TITLE
IndexedDB as a persistence option?

### ISSUE THREAD

**Issue by MirjamElad** [DallasHoff/sqlocal#19]
Hi,
SQLocale uses sqlite-wasm which to the best of my knowledge only uses OPFS for persisting data.
There could be other options. For instance absurd-sql uses IndexedDB for storing data.
Since OPFS is not widely and fully supported yet. Would you consider adding the option to use IndexedDB?
How much work would it be to let sqlocale wrap absurd-sql as an option?'
Thank you again!

**Comment by jorbuedo** [comment]
Probably better to use https://github.com/rhashimoto/wa-sqlite 
absurd-sql was a proof of concept and not mantained

**Comment by DallasHoff** [comment]
OPFS actually is widely supported these days. SQLocal fully works in all modern browsers in the versions released since last March. It should also have better performance than an IndexDB-based solution.

The benefit of being based on sqlite-wasm is that package is built by the actual SQLite team and so fully implements all of SQLite3's features with all of the compatibility guarantees that the SQLite project normally provides. I don't think building a second version of SQLocal around an experimental and incomplete implementation of SQLite like Absurd-SQL is a good idea or useful for anyone.
