### ISSUE TITLE
Table creation and migrations with Drizzle

### ISSUE THREAD

**Issue by fenicento** [DallasHoff/sqlocal#32]
Hi, let me start by saying thank you! This library is a wonderful and much needed, I hope you'll keep developing and maintaining it. Right now I'm experimenting the Drizzle integration, which works fine except for the table creation and alteration. These tasks are handled by [drizzle-kit](https://orm.drizzle.team/kit-docs/overview), which AFAIK is not usable with sqlocal (it's just not possible to point the path to the SQLite file).

To overcome this I'm generating the tables by directly injecting the necessary sql:

```javascript
import { SQLocalDrizzle } from 'sqlocal/drizzle';
import { drizzle } from 'drizzle-orm/sqlite-proxy';


const { sql, driver, batchDriver } = new SQLocalDrizzle('database.db');

await sql`CREATE TABLE IF NOT EXISTS institutions (
	created_at integer NOT NULL,
	updated_at integer NOT NULL,
	_id integer PRIMARY KEY NOT NULL,
	name text NOT NULL,
	description text,
	country text,
	license text,
	address text,
	link text
);`

//etc... 

export const db = drizzle(driver, batchDriver);
``` 
This is a bit uncomfortable as I have to rewrite the table definitions and alterations each time I make some changes to the schema. Is there any way to use `drizzle-kit` with OPFS SQlite?

**Comment by DallasHoff** [comment]
Running migrations in the browser with Drizzle Kit currently is not possible because their `migrate` function relies on Node.js built-in packages. I opened [an issue](https://github.com/drizzle-team/drizzle-orm/issues/1009) a while back (give it a thumbs up) offering to help implement a solution for this, including a browser-compatible `migrate` function and a way for Drizzle Kit to bundle the generated migrations together. Unfortunately, the Drizzle team has not prioritized it yet.

For now, you may consider doing something similar to what I did [here](https://github.com/DallasHoff/drizzle-browser-migrate) to implement your own version of the `migrate` function. This has the drawback that Drizzle Kit does not have the functionality to bundle the migrations for you, and you will need to ensure that the `migrate` function remains compatible with any Drizzle Kit updates which may happen before Drizzle goes 1.0. In fact, they [recently announced](https://github.com/drizzle-team/drizzle-orm/discussions/2624) some new plans around migrations.

Another option you have is to use Kysely for migrations instead. You can write Kysely migrations as I have written [here](https://sqlocal.dallashoffman.com/kysely/migrations) and use it alongside Drizzle. You can even use your Drizzle schema to define your Kysely schema as shown [here](https://github.com/drizzle-team/drizzle-kysely) if you wish to use more features of Kysely.

I would like to better support Drizzle migrations, but Drizzle is still working toward a 1.0 release and Drizzle Kit has not been open-sourced yet, which makes things somewhat difficult. If those things change and the Drizzle team still has not acknowledged my offer to contribute, I may build something into sqlocal to bridge the gap.

**Comment by fenicento** [comment]
Thanks for the thorough reply. I added a +1 to your drizzle issue, in the meanwhile I'll check your proposal.

**Comment by DallasHoff** [comment]
Closing this, but let me know if there's anything else.
