### ISSUE TITLE
Query in application-defined function freezes SQLocal

### ISSUE THREAD

**Issue by davidisaaclee** [DallasHoff/sqlocal#43]
I'm adding a user-defined function `build_my_row()` using `createScalarFunction`. In the definition of `build_my_row()`, I want to query the database to collect some data.[0]

My code looks roughly like this:

```ts
await sqlocal.createScalarFunction(
  "build_my_row",
  async (): Promise<<MyRow> => {
    return buildRow(
      await db.selectFrom('widgets').select('name').execute()
    );
  }
);

// elsewhere...
sql`build_my_row()`.execute(db);
```

This locks up SQLocal – I think this is due to [`initMutex`](https://github.com/DallasHoff/sqlocal/blob/8031caacffc19367c865a2f15b79c12fd66687d1/src/processor.ts#L100) in `processor.ts`:

1. `build_my_row` is invoked from JS
2. SQLocal processor locks `initMutex`, then tells SQLite to exec `build_my_row`
3. `build_my_row` jumps back to JS
4. JS starts the inner query of `build_my_row`
5. SQLocal processor attempts to take `initMutex` – but the lock from step 2 hasn't been released yet

Here's a repro (I'm running this in a Vite vanilla starter): https://gist.github.com/davidisaaclee/088527ecc352a0fb1d3e0b160de7f35e

It looks like the goal of `InitMutex` is to avoid running commands before everything's ready. If there's need to lock after we know that init has finished, maybe we could add a bool once we know init is done? e.g. `isReadyForQueries || initMutex.lock()`.[1]

---

[0] I think this is a valid use of application-defined functions – SQLite docs say [_An application-defined function is permitted to call other SQLite interfaces_](https://www.sqlite.org/c3ref/create_function.html). 

[1] Tried this here https://github.com/davidisaaclee/sqlocal/commit/bac8d873087c90233ef14ae9a8d42535ee2929d5 and it doesn't seem to fix in my usage. I don't know how to attach a debugger to the worker, so it's hard for me to debug. https://github.com/davidisaaclee/sqlocal/commit/5937d7ced5e09500045f33a48d8d32f5ff7ccdec also does not appear to work.

**Comment by DallasHoff** [comment]
The `initMutex` is actually not the cause of this. The issue is that user-defined functions must be synchronous from SQLite's perspective. Though since the UDF is on the main thread while sqlite-wasm runs in a worker thread, there is necessarily some asynchronous communication that needs to take place between the threads. The way SQLocal gets around this is while the UDF is running, the worker thread is suspended/blocked until the UDF returns. This way, the UDF returns synchronously from the worker thread's perspective.

The result of this is that you have a way to call out to main thread logic inside a SQL query, and the UDF can even return a Promise, but the worker cannot process subsequent SQL queries until after the UDF returns.

You should be able to work around this by having a second instance of `SQLocal` pointed at the same database and using that to make the query inside the UDF. The second instance will have its own worker thread which will not be blocked by the pending UDF. Just keep in mind that the data the second instance has access to will not include changes from uncommitted transactions from the first instance.

I'd also note that you may be able to avoid making a query within a UDF by refactoring your query to do a subquery instead of a UDF, but I don't know the full details of your use case here, so whether that will work is for you to decide.

Hope this helps!

**Comment by davidisaaclee** [comment]
Thank you, that makes sense. I'll give your workaround a try and reopen if it doesn't work.

fwiw, my use case: I have data in "API shapes" in my database (which I want to keep), and want to derive lossy "application shape" models from those - so I'm setting up triggers to build the app shape rows from the existing DB whenever an app model's dependency gets updated. So I want to define reusable functions (e.g. API model to hash or to app model) for those triggers, since I'll be attaching triggers creating a specific app model to multiple API model tables.
