### ISSUE TITLE
PRAGMAs not persisted

### ISSUE THREAD

**Issue by ashokgelal** [DallasHoff/sqlocal#53]
I'm using SQLocal with Drizzle ORM (along with the migration code that you have shared in a separate repo) and no matter what I try PRAGMA statements are never seem to have any effect. I've tried:

```ts
import * as schema from './schema'

const DB_NAME = 'test.db'

const { driver, batchDriver } = new SQLocalDrizzle(DB_NAME)
const db = drizzle(driver, batchDriver, {
  schema,
})

db.run(sql`PRAGMA foreign_keys = ON`)
db.run(sql`PRAGMA journal_mode = WAL`)

```

Is this the right way to execute those pragmas or am I doing something very stupid? Thank you!

**Comment by ashokgelal** [comment]
Something else that I've tried:

```ts
const { driver, batchDriver, sql } = new SQLocalDrizzle(DB_NAME)
const db = drizzle(driver, batchDriver, {
  schema,
})

sql(`PRAGMA journal_mode = WAL`).then((walResult) => {
  console.log(walResult); // prints delete; expecting WAL
  sql(`PRAGMA foreign_keys = ON`).then((foreignResult) => {
    console.log(foreignResult) // prints []
  })
})

**Comment by ashokgelal** [comment]
I ran the sticky-notes demo app, which has FOREIGN_KEYS pragma enabled (https://github.com/DallasHoff/sticky-notes/blob/45f446e2f3e80243cfad027a7f87e89ace499aa3/src/lib/db/migrator.ts#L15), downloaded the db file, and when checking the db, it shows me that it is actually turned off (see attached).

![CleanShot 2024-11-08 at 10 24 54@2x](https://github.com/user-attachments/assets/305dfe7a-a359-4555-8386-c3d4fc88d54e)

**Comment by DallasHoff** [comment]
In SQLite, PRAGMAs are settings that only apply to the current connection, so if you run a PRAGMA command only once, such as in a migration, that change will not persist to the next session. Similarly, downloading the database file and checking the PRAGMAs in another program like you did will show the default values because that's also a new connection. 

If you want to change PRAGMA settings, you need to do it whenever you open a new connection to the database. `SQLocal` has an [`onConnect`](https://sqlocal.dallashoffman.com/guide/setup#options) hook for this.

**Comment by ashokgelal** [comment]
Ah! Thank you. I got the foreign_keys working but still not sure if journal_mode is working. This is what I have:

```ts
const {
  driver,
  batchDriver,
  sql,
} = new SQLocalDrizzle({
  databasePath: 'test.db',
  onConnect: async () => {
    await sql`PRAGMA journal_mode = WAL;`
    await sql`PRAGMA foreign_keys = ON;`
    console.log(await sql`PRAGMA foreign_keys;`) // returns foreign_keys  =  1
    console.log(await sql`PRAGMA journal_mode;`) // still returns journal_model = delete
  },
})```

Is that expected as well? Do you have any insights? Than you!

**Comment by DallasHoff** [comment]
I did a bit of research. It looks like WAL mode is actually not supported in the WASM build of SQLite due to limitations in the OPFS APIs of browsers. That's why `PRAGMA journal_mode = WAL` is ignored. They have not ruled out the possibility of WAL support in the future though if browsers implement certain proposed changes to the OPFS API.

Lack of support for WAL mode in sqlite-wasm is somewhat disappointing, but it's probably fine. WAL support isn't as important in a browser environment because, compared to a server environment, you are much less likely to have multiple connections all attempting to read and write to the database at the same time, so the benefits WAL mode bring are unnecessary. Concurrent reads will just be delayed by a few milliseconds.

**Comment by ashokgelal** [comment]
I appreciate you looking into it.  Thank you!
