### ISSUE TITLE
Is sqlite-vec supported?

### ISSUE THREAD

**Issue by nfplay** [DallasHoff/sqlocal#57]
Pretty much the question: is there a way to support sqlite-vec?

Thanks in advance,
Nuno

**Comment by DallasHoff** [comment]
Since `sqlite-wasm` does not support dynamically loading extensions, you will have to recompile `sqlite-wasm` in order to add the `sqlite-vec` extension to it. They have documentation about how to do that [here](https://sqlite.org/wasm/doc/trunk/building.md#extra-init).

There was also a demo that Ben Holmes did where he implemented vector search with SQLocal by just storing the vectors as BLOBs, so you can check out that [video](https://www.youtube.com/watch?v=vwF1AdVk2o8) and see if it might fit your use case.
